### ISSUE TITLE
Непонятно, это какая ДЗ

### ISSUE THREAD

**Issue by coursar** [flashxxx2/githubdocker#1]

**Comment by flashxxx2** [comment]
согласно этой инструкции https://github.com/coursar/javaII/tree/master/01_docker, ссылка на нее была в презентации

**Comment by coursar** [comment]
Ок, но там вроде как по требованиям нужно было ещё научить сервер обрабатывать разные пути и методы

**Comment by flashxxx2** [comment]
Я это требование не сделал, тут только создание образа и публикация его на гит хабе
